Development
wasabi-dev/cleanworldedinburgh pull request #8
Opened 2020-06-26 21:44 UTC by lobogris26

2020-06-26 22:18 UTC, lobogris26 commented
mas cambios

2020-06-26 22:18 UTC, lobogris26 commented
cambio

2020-06-28 00:41 UTC, Cyntique approved these changes

2020-06-28 00:41 UTC, Cyntique commented on css/style.scss
>    width: 100%;
Agregar cambio

2020-06-28 00:52 UTC, Cyntique requested changes
Prueba

2020-06-28 00:57 UTC, merged